// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MovieProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MovieProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MovieProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MovieProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UserProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UserProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UserProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UserProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MovieTag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MovieTag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_UserRatingList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_UserRatingList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MovieProfile2Sim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MovieProfile2Sim_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_similarMovies_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_similarMovies_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MovieRelevance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MovieRelevance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RecallResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RecallResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RecommendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RecommendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RecommendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RecommendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\";\n\023MovieP" +
      "rofileRequest\022\022\n\nsession_id\030\001 \001(\t\022\020\n\010mov" +
      "ie_id\030\002 \001(\004\"\316\001\n\024MovieProfileResponse\022\022\n\n" +
      "session_id\030\001 \001(\t\022\020\n\010movie_id\030\002 \001(\004\022\"\n\004ta" +
      "gs\030\003 \003(\0132\024.helloworld.MovieTag\022\r\n\005title\030" +
      "\004 \001(\t\022\016\n\006rating\030\005 \001(\001\022\016\n\006genres\030\006 \001(\t\022\023\n" +
      "\013prefer_year\030\007 \001(\t\022(\n\nsortedTags\030\010 \003(\0132\024" +
      ".helloworld.MovieTag\"9\n\022UserProfileReque" +
      "st\022\022\n\nsession_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\004\"" +
      "\345\001\n\023UserProfileResponse\022\022\n\nsession_id\030\001 ",
      "\001(\t\022\017\n\007user_id\030\002 \001(\004\022.\n\nratingList\030\003 \003(\013" +
      "2\032.helloworld.UserRatingList\022\"\n\004tags\030\004 \003" +
      "(\0132\024.helloworld.MovieTag\022\026\n\016average_rati" +
      "ng\030\005 \001(\001\022\023\n\013prefer_year\030\006 \001(\t\022(\n\nsortedT" +
      "ags\030\007 \003(\0132\024.helloworld.MovieTag\"-\n\010Movie" +
      "Tag\022\016\n\006tag_id\030\001 \001(\004\022\021\n\trelevance\030\002 \001(\001\"E" +
      "\n\016UserRatingList\022\020\n\010movie_id\030\001 \001(\004\022\016\n\006ra" +
      "ting\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001(\004\"^\n\020MoviePr" +
      "ofile2Sim\0227\n\rmovie_profile\030\001 \001(\0132 .hello" +
      "world.MovieProfileResponse\022\021\n\trelevance\030",
      "\002 \001(\001\"U\n\rsimilarMovies\022\020\n\010movie_id\030\001 \001(\004" +
      "\0222\n\016movieRelevance\030\002 \003(\0132\032.helloworld.Mo" +
      "vieRelevance\"5\n\016MovieRelevance\022\020\n\010movie_" +
      "id\030\001 \001(\004\022\021\n\trelevance\030\002 \001(\001\"/\n\014RecallRes" +
      "ult\022\016\n\006userId\030\001 \001(\t\022\017\n\007movieId\030\002 \003(\t\"6\n\020" +
      "RecommendRequest\022\022\n\nsession_id\030\001 \001(\t\022\016\n\006" +
      "userId\030\002 \001(\t\"]\n\021RecommendResponse\022\022\n\nses" +
      "sion_id\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\017\n\007movieId" +
      "\030\003 \003(\t\022\023\n\013possibility\030\004 \003(\t2\213\002\n\007Greeter\022" +
      "V\n\017GetMovieProfile\022\037.helloworld.MoviePro",
      "fileRequest\032 .helloworld.MovieProfileRes" +
      "ponse\"\000\022S\n\016GetUserProfile\022\036.helloworld.U" +
      "serProfileRequest\032\037.helloworld.UserProfi" +
      "leResponse\"\000\022S\n\022GetRecommendMovies\022\034.hel" +
      "loworld.RecommendRequest\032\035.helloworld.Re" +
      "commendResponse\"\000B6\n\033io.grpc.examples.he" +
      "lloworldB\017HelloWorldProtoP\001\242\002\003HLWb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_MovieProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_MovieProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MovieProfileRequest_descriptor,
        new String[] { "SessionId", "MovieId", });
    internal_static_helloworld_MovieProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_MovieProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MovieProfileResponse_descriptor,
        new String[] { "SessionId", "MovieId", "Tags", "Title", "Rating", "Genres", "PreferYear", "SortedTags", });
    internal_static_helloworld_UserProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_UserProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UserProfileRequest_descriptor,
        new String[] { "SessionId", "UserId", });
    internal_static_helloworld_UserProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_UserProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UserProfileResponse_descriptor,
        new String[] { "SessionId", "UserId", "RatingList", "Tags", "AverageRating", "PreferYear", "SortedTags", });
    internal_static_helloworld_MovieTag_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_MovieTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MovieTag_descriptor,
        new String[] { "TagId", "Relevance", });
    internal_static_helloworld_UserRatingList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helloworld_UserRatingList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_UserRatingList_descriptor,
        new String[] { "MovieId", "Rating", "Timestamp", });
    internal_static_helloworld_MovieProfile2Sim_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helloworld_MovieProfile2Sim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MovieProfile2Sim_descriptor,
        new String[] { "MovieProfile", "Relevance", });
    internal_static_helloworld_similarMovies_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_helloworld_similarMovies_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_similarMovies_descriptor,
        new String[] { "MovieId", "MovieRelevance", });
    internal_static_helloworld_MovieRelevance_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_helloworld_MovieRelevance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MovieRelevance_descriptor,
        new String[] { "MovieId", "Relevance", });
    internal_static_helloworld_RecallResult_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_helloworld_RecallResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RecallResult_descriptor,
        new String[] { "UserId", "MovieId", });
    internal_static_helloworld_RecommendRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_helloworld_RecommendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RecommendRequest_descriptor,
        new String[] { "SessionId", "UserId", });
    internal_static_helloworld_RecommendResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_helloworld_RecommendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RecommendResponse_descriptor,
        new String[] { "SessionId", "UserId", "MovieId", "Possibility", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
