// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface MovieTagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.MovieTag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 tag_id = 1;</code>
   */
  long getTagId();

  /**
   * <code>optional double relevance = 2;</code>
   */
  double getRelevance();
}
