// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface MovieProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.MovieProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string session_id = 1;</code>
   */
  String getSessionId();
  /**
   * <code>optional string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional uint64 movie_id = 2;</code>
   */
  long getMovieId();

  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  java.util.List<MovieTag>
      getTagsList();
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  MovieTag getTags(int index);
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  java.util.List<? extends MovieTagOrBuilder>
      getTagsOrBuilderList();
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  MovieTagOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>optional string title = 4;</code>
   */
  String getTitle();
  /**
   * <code>optional string title = 4;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional double rating = 5;</code>
   */
  double getRating();

  /**
   * <code>optional string genres = 6;</code>
   */
  String getGenres();
  /**
   * <code>optional string genres = 6;</code>
   */
  com.google.protobuf.ByteString
      getGenresBytes();

  /**
   * <code>optional string prefer_year = 7;</code>
   */
  String getPreferYear();
  /**
   * <code>optional string prefer_year = 7;</code>
   */
  com.google.protobuf.ByteString
      getPreferYearBytes();

  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  java.util.List<MovieTag>
      getSortedTagsList();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  MovieTag getSortedTags(int index);
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  int getSortedTagsCount();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  java.util.List<? extends MovieTagOrBuilder>
      getSortedTagsOrBuilderList();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  MovieTagOrBuilder getSortedTagsOrBuilder(
      int index);
}
