// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface MovieRelevanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.MovieRelevance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 movie_id = 1;</code>
   */
  long getMovieId();

  /**
   * <code>optional double relevance = 2;</code>
   */
  double getRelevance();
}
