// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

/**
 * Protobuf type {@code helloworld.MovieProfileResponse}
 */
public  final class MovieProfileResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.MovieProfileResponse)
    MovieProfileResponseOrBuilder {
  // Use MovieProfileResponse.newBuilder() to construct.
  private MovieProfileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieProfileResponse() {
    sessionId_ = "";
    movieId_ = 0L;
    tags_ = java.util.Collections.emptyList();
    title_ = "";
    rating_ = 0D;
    genres_ = "";
    preferYear_ = "";
    sortedTags_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MovieProfileResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            sessionId_ = s;
            break;
          }
          case 16: {

            movieId_ = input.readUInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tags_ = new java.util.ArrayList<MovieTag>();
              mutable_bitField0_ |= 0x00000004;
            }
            tags_.add(
                input.readMessage(MovieTag.parser(), extensionRegistry));
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 41: {

            rating_ = input.readDouble();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            genres_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            preferYear_ = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              sortedTags_ = new java.util.ArrayList<MovieTag>();
              mutable_bitField0_ |= 0x00000080;
            }
            sortedTags_.add(
                input.readMessage(MovieTag.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        tags_ = java.util.Collections.unmodifiableList(tags_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        sortedTags_ = java.util.Collections.unmodifiableList(sortedTags_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_helloworld_MovieProfileResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_helloworld_MovieProfileResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MovieProfileResponse.class, Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private volatile Object sessionId_;
  /**
   * <code>optional string session_id = 1;</code>
   */
  public String getSessionId() {
    Object ref = sessionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string session_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    Object ref = sessionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOVIE_ID_FIELD_NUMBER = 2;
  private long movieId_;
  /**
   * <code>optional uint64 movie_id = 2;</code>
   */
  public long getMovieId() {
    return movieId_;
  }

  public static final int TAGS_FIELD_NUMBER = 3;
  private java.util.List<MovieTag> tags_;
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  public java.util.List<MovieTag> getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  public java.util.List<? extends MovieTagOrBuilder>
      getTagsOrBuilderList() {
    return tags_;
  }
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  public MovieTag getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated .helloworld.MovieTag tags = 3;</code>
   */
  public MovieTagOrBuilder getTagsOrBuilder(
      int index) {
    return tags_.get(index);
  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private volatile Object title_;
  /**
   * <code>optional string title = 4;</code>
   */
  public String getTitle() {
    Object ref = title_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>optional string title = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    Object ref = title_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 5;
  private double rating_;
  /**
   * <code>optional double rating = 5;</code>
   */
  public double getRating() {
    return rating_;
  }

  public static final int GENRES_FIELD_NUMBER = 6;
  private volatile Object genres_;
  /**
   * <code>optional string genres = 6;</code>
   */
  public String getGenres() {
    Object ref = genres_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      genres_ = s;
      return s;
    }
  }
  /**
   * <code>optional string genres = 6;</code>
   */
  public com.google.protobuf.ByteString
      getGenresBytes() {
    Object ref = genres_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      genres_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREFER_YEAR_FIELD_NUMBER = 7;
  private volatile Object preferYear_;
  /**
   * <code>optional string prefer_year = 7;</code>
   */
  public String getPreferYear() {
    Object ref = preferYear_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      preferYear_ = s;
      return s;
    }
  }
  /**
   * <code>optional string prefer_year = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPreferYearBytes() {
    Object ref = preferYear_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      preferYear_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SORTEDTAGS_FIELD_NUMBER = 8;
  private java.util.List<MovieTag> sortedTags_;
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  public java.util.List<MovieTag> getSortedTagsList() {
    return sortedTags_;
  }
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  public java.util.List<? extends MovieTagOrBuilder>
      getSortedTagsOrBuilderList() {
    return sortedTags_;
  }
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  public int getSortedTagsCount() {
    return sortedTags_.size();
  }
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  public MovieTag getSortedTags(int index) {
    return sortedTags_.get(index);
  }
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
   */
  public MovieTagOrBuilder getSortedTagsOrBuilder(
      int index) {
    return sortedTags_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
    }
    if (movieId_ != 0L) {
      output.writeUInt64(2, movieId_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      output.writeMessage(3, tags_.get(i));
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
    }
    if (rating_ != 0D) {
      output.writeDouble(5, rating_);
    }
    if (!getGenresBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, genres_);
    }
    if (!getPreferYearBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, preferYear_);
    }
    for (int i = 0; i < sortedTags_.size(); i++) {
      output.writeMessage(8, sortedTags_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
    }
    if (movieId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, movieId_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tags_.get(i));
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
    }
    if (rating_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, rating_);
    }
    if (!getGenresBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, genres_);
    }
    if (!getPreferYearBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, preferYear_);
    }
    for (int i = 0; i < sortedTags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, sortedTags_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MovieProfileResponse)) {
      return super.equals(obj);
    }
    MovieProfileResponse other = (MovieProfileResponse) obj;

    boolean result = true;
    result = result && getSessionId()
        .equals(other.getSessionId());
    result = result && (getMovieId()
        == other.getMovieId());
    result = result && getTagsList()
        .equals(other.getTagsList());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && (
        Double.doubleToLongBits(getRating())
        == Double.doubleToLongBits(
            other.getRating()));
    result = result && getGenres()
        .equals(other.getGenres());
    result = result && getPreferYear()
        .equals(other.getPreferYear());
    result = result && getSortedTagsList()
        .equals(other.getSortedTagsList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + MOVIE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMovieId());
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getRating()));
    hash = (37 * hash) + GENRES_FIELD_NUMBER;
    hash = (53 * hash) + getGenres().hashCode();
    hash = (37 * hash) + PREFER_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getPreferYear().hashCode();
    if (getSortedTagsCount() > 0) {
      hash = (37 * hash) + SORTEDTAGS_FIELD_NUMBER;
      hash = (53 * hash) + getSortedTagsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MovieProfileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieProfileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieProfileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieProfileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieProfileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieProfileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieProfileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MovieProfileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MovieProfileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.MovieProfileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.MovieProfileResponse)
      MovieProfileResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_helloworld_MovieProfileResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_helloworld_MovieProfileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MovieProfileResponse.class, Builder.class);
    }

    // Construct using io.grpc.examples.helloworld.MovieProfileResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTagsFieldBuilder();
        getSortedTagsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      sessionId_ = "";

      movieId_ = 0L;

      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        tagsBuilder_.clear();
      }
      title_ = "";

      rating_ = 0D;

      genres_ = "";

      preferYear_ = "";

      if (sortedTagsBuilder_ == null) {
        sortedTags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        sortedTagsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_helloworld_MovieProfileResponse_descriptor;
    }

    public MovieProfileResponse getDefaultInstanceForType() {
      return MovieProfileResponse.getDefaultInstance();
    }

    public MovieProfileResponse build() {
      MovieProfileResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public MovieProfileResponse buildPartial() {
      MovieProfileResponse result = new MovieProfileResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.sessionId_ = sessionId_;
      result.movieId_ = movieId_;
      if (tagsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      result.title_ = title_;
      result.rating_ = rating_;
      result.genres_ = genres_;
      result.preferYear_ = preferYear_;
      if (sortedTagsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          sortedTags_ = java.util.Collections.unmodifiableList(sortedTags_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.sortedTags_ = sortedTags_;
      } else {
        result.sortedTags_ = sortedTagsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MovieProfileResponse) {
        return mergeFrom((MovieProfileResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MovieProfileResponse other) {
      if (other == MovieProfileResponse.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        onChanged();
      }
      if (other.getMovieId() != 0L) {
        setMovieId(other.getMovieId());
      }
      if (tagsBuilder_ == null) {
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
      } else {
        if (!other.tags_.isEmpty()) {
          if (tagsBuilder_.isEmpty()) {
            tagsBuilder_.dispose();
            tagsBuilder_ = null;
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tagsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTagsFieldBuilder() : null;
          } else {
            tagsBuilder_.addAllMessages(other.tags_);
          }
        }
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.getRating() != 0D) {
        setRating(other.getRating());
      }
      if (!other.getGenres().isEmpty()) {
        genres_ = other.genres_;
        onChanged();
      }
      if (!other.getPreferYear().isEmpty()) {
        preferYear_ = other.preferYear_;
        onChanged();
      }
      if (sortedTagsBuilder_ == null) {
        if (!other.sortedTags_.isEmpty()) {
          if (sortedTags_.isEmpty()) {
            sortedTags_ = other.sortedTags_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureSortedTagsIsMutable();
            sortedTags_.addAll(other.sortedTags_);
          }
          onChanged();
        }
      } else {
        if (!other.sortedTags_.isEmpty()) {
          if (sortedTagsBuilder_.isEmpty()) {
            sortedTagsBuilder_.dispose();
            sortedTagsBuilder_ = null;
            sortedTags_ = other.sortedTags_;
            bitField0_ = (bitField0_ & ~0x00000080);
            sortedTagsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSortedTagsFieldBuilder() : null;
          } else {
            sortedTagsBuilder_.addAllMessages(other.sortedTags_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MovieProfileResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MovieProfileResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object sessionId_ = "";
    /**
     * <code>optional string session_id = 1;</code>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public Builder setSessionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public Builder clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_id = 1;</code>
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionId_ = value;
      onChanged();
      return this;
    }

    private long movieId_ ;
    /**
     * <code>optional uint64 movie_id = 2;</code>
     */
    public long getMovieId() {
      return movieId_;
    }
    /**
     * <code>optional uint64 movie_id = 2;</code>
     */
    public Builder setMovieId(long value) {
      
      movieId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 movie_id = 2;</code>
     */
    public Builder clearMovieId() {
      
      movieId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<MovieTag> tags_ =
      java.util.Collections.emptyList();
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        tags_ = new java.util.ArrayList<MovieTag>(tags_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieTag, MovieTag.Builder, MovieTagOrBuilder> tagsBuilder_;

    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public java.util.List<MovieTag> getTagsList() {
      if (tagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tags_);
      } else {
        return tagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public int getTagsCount() {
      if (tagsBuilder_ == null) {
        return tags_.size();
      } else {
        return tagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public MovieTag getTags(int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);
      } else {
        return tagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder setTags(
        int index, MovieTag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder setTags(
        int index, MovieTag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder addTags(MovieTag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder addTags(
        int index, MovieTag value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(index, value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder addTags(
        MovieTag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder addTags(
        int index, MovieTag.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder addAllTags(
        Iterable<? extends MovieTag> values) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
      } else {
        tagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public Builder removeTags(int index) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.remove(index);
        onChanged();
      } else {
        tagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public MovieTag.Builder getTagsBuilder(
        int index) {
      return getTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public MovieTagOrBuilder getTagsOrBuilder(
        int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);  } else {
        return tagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public java.util.List<? extends MovieTagOrBuilder>
         getTagsOrBuilderList() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tags_);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public MovieTag.Builder addTagsBuilder() {
      return getTagsFieldBuilder().addBuilder(
          MovieTag.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public MovieTag.Builder addTagsBuilder(
        int index) {
      return getTagsFieldBuilder().addBuilder(
          index, MovieTag.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieTag tags = 3;</code>
     */
    public java.util.List<MovieTag.Builder>
         getTagsBuilderList() {
      return getTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieTag, MovieTag.Builder, MovieTagOrBuilder>
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MovieTag, MovieTag.Builder, MovieTagOrBuilder>(
                tags_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }

    private Object title_ = "";
    /**
     * <code>optional string title = 4;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string title = 4;</code>
     */
    public Builder setTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 4;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>optional string title = 4;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private double rating_ ;
    /**
     * <code>optional double rating = 5;</code>
     */
    public double getRating() {
      return rating_;
    }
    /**
     * <code>optional double rating = 5;</code>
     */
    public Builder setRating(double value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double rating = 5;</code>
     */
    public Builder clearRating() {
      
      rating_ = 0D;
      onChanged();
      return this;
    }

    private Object genres_ = "";
    /**
     * <code>optional string genres = 6;</code>
     */
    public String getGenres() {
      Object ref = genres_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        genres_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string genres = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGenresBytes() {
      Object ref = genres_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        genres_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string genres = 6;</code>
     */
    public Builder setGenres(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      genres_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string genres = 6;</code>
     */
    public Builder clearGenres() {
      
      genres_ = getDefaultInstance().getGenres();
      onChanged();
      return this;
    }
    /**
     * <code>optional string genres = 6;</code>
     */
    public Builder setGenresBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      genres_ = value;
      onChanged();
      return this;
    }

    private Object preferYear_ = "";
    /**
     * <code>optional string prefer_year = 7;</code>
     */
    public String getPreferYear() {
      Object ref = preferYear_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        preferYear_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string prefer_year = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPreferYearBytes() {
      Object ref = preferYear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        preferYear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string prefer_year = 7;</code>
     */
    public Builder setPreferYear(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preferYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string prefer_year = 7;</code>
     */
    public Builder clearPreferYear() {
      
      preferYear_ = getDefaultInstance().getPreferYear();
      onChanged();
      return this;
    }
    /**
     * <code>optional string prefer_year = 7;</code>
     */
    public Builder setPreferYearBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preferYear_ = value;
      onChanged();
      return this;
    }

    private java.util.List<MovieTag> sortedTags_ =
      java.util.Collections.emptyList();
    private void ensureSortedTagsIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        sortedTags_ = new java.util.ArrayList<MovieTag>(sortedTags_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieTag, MovieTag.Builder, MovieTagOrBuilder> sortedTagsBuilder_;

    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public java.util.List<MovieTag> getSortedTagsList() {
      if (sortedTagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sortedTags_);
      } else {
        return sortedTagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public int getSortedTagsCount() {
      if (sortedTagsBuilder_ == null) {
        return sortedTags_.size();
      } else {
        return sortedTagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public MovieTag getSortedTags(int index) {
      if (sortedTagsBuilder_ == null) {
        return sortedTags_.get(index);
      } else {
        return sortedTagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder setSortedTags(
        int index, MovieTag value) {
      if (sortedTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortedTagsIsMutable();
        sortedTags_.set(index, value);
        onChanged();
      } else {
        sortedTagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder setSortedTags(
        int index, MovieTag.Builder builderForValue) {
      if (sortedTagsBuilder_ == null) {
        ensureSortedTagsIsMutable();
        sortedTags_.set(index, builderForValue.build());
        onChanged();
      } else {
        sortedTagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder addSortedTags(MovieTag value) {
      if (sortedTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortedTagsIsMutable();
        sortedTags_.add(value);
        onChanged();
      } else {
        sortedTagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder addSortedTags(
        int index, MovieTag value) {
      if (sortedTagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSortedTagsIsMutable();
        sortedTags_.add(index, value);
        onChanged();
      } else {
        sortedTagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder addSortedTags(
        MovieTag.Builder builderForValue) {
      if (sortedTagsBuilder_ == null) {
        ensureSortedTagsIsMutable();
        sortedTags_.add(builderForValue.build());
        onChanged();
      } else {
        sortedTagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder addSortedTags(
        int index, MovieTag.Builder builderForValue) {
      if (sortedTagsBuilder_ == null) {
        ensureSortedTagsIsMutable();
        sortedTags_.add(index, builderForValue.build());
        onChanged();
      } else {
        sortedTagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder addAllSortedTags(
        Iterable<? extends MovieTag> values) {
      if (sortedTagsBuilder_ == null) {
        ensureSortedTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sortedTags_);
        onChanged();
      } else {
        sortedTagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder clearSortedTags() {
      if (sortedTagsBuilder_ == null) {
        sortedTags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        sortedTagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public Builder removeSortedTags(int index) {
      if (sortedTagsBuilder_ == null) {
        ensureSortedTagsIsMutable();
        sortedTags_.remove(index);
        onChanged();
      } else {
        sortedTagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public MovieTag.Builder getSortedTagsBuilder(
        int index) {
      return getSortedTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public MovieTagOrBuilder getSortedTagsOrBuilder(
        int index) {
      if (sortedTagsBuilder_ == null) {
        return sortedTags_.get(index);  } else {
        return sortedTagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public java.util.List<? extends MovieTagOrBuilder>
         getSortedTagsOrBuilderList() {
      if (sortedTagsBuilder_ != null) {
        return sortedTagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sortedTags_);
      }
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public MovieTag.Builder addSortedTagsBuilder() {
      return getSortedTagsFieldBuilder().addBuilder(
          MovieTag.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public MovieTag.Builder addSortedTagsBuilder(
        int index) {
      return getSortedTagsFieldBuilder().addBuilder(
          index, MovieTag.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieTag sortedTags = 8;</code>
     */
    public java.util.List<MovieTag.Builder>
         getSortedTagsBuilderList() {
      return getSortedTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieTag, MovieTag.Builder, MovieTagOrBuilder>
        getSortedTagsFieldBuilder() {
      if (sortedTagsBuilder_ == null) {
        sortedTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MovieTag, MovieTag.Builder, MovieTagOrBuilder>(
                sortedTags_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        sortedTags_ = null;
      }
      return sortedTagsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:helloworld.MovieProfileResponse)
  }

  // @@protoc_insertion_point(class_scope:helloworld.MovieProfileResponse)
  private static final MovieProfileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MovieProfileResponse();
  }

  public static MovieProfileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieProfileResponse>
      PARSER = new com.google.protobuf.AbstractParser<MovieProfileResponse>() {
    public MovieProfileResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieProfileResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieProfileResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MovieProfileResponse> getParserForType() {
    return PARSER;
  }

  public MovieProfileResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

