// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

/**
 * Protobuf type {@code helloworld.MovieProfile2Sim}
 */
public  final class MovieProfile2Sim extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.MovieProfile2Sim)
    MovieProfile2SimOrBuilder {
  // Use MovieProfile2Sim.newBuilder() to construct.
  private MovieProfile2Sim(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieProfile2Sim() {
    relevance_ = 0D;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MovieProfile2Sim(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            MovieProfileResponse.Builder subBuilder = null;
            if (movieProfile_ != null) {
              subBuilder = movieProfile_.toBuilder();
            }
            movieProfile_ = input.readMessage(MovieProfileResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(movieProfile_);
              movieProfile_ = subBuilder.buildPartial();
            }

            break;
          }
          case 17: {

            relevance_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_helloworld_MovieProfile2Sim_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_helloworld_MovieProfile2Sim_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MovieProfile2Sim.class, Builder.class);
  }

  public static final int MOVIE_PROFILE_FIELD_NUMBER = 1;
  private MovieProfileResponse movieProfile_;
  /**
   * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
   */
  public boolean hasMovieProfile() {
    return movieProfile_ != null;
  }
  /**
   * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
   */
  public MovieProfileResponse getMovieProfile() {
    return movieProfile_ == null ? MovieProfileResponse.getDefaultInstance() : movieProfile_;
  }
  /**
   * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
   */
  public MovieProfileResponseOrBuilder getMovieProfileOrBuilder() {
    return getMovieProfile();
  }

  public static final int RELEVANCE_FIELD_NUMBER = 2;
  private double relevance_;
  /**
   * <code>optional double relevance = 2;</code>
   */
  public double getRelevance() {
    return relevance_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (movieProfile_ != null) {
      output.writeMessage(1, getMovieProfile());
    }
    if (relevance_ != 0D) {
      output.writeDouble(2, relevance_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (movieProfile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMovieProfile());
    }
    if (relevance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, relevance_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MovieProfile2Sim)) {
      return super.equals(obj);
    }
    MovieProfile2Sim other = (MovieProfile2Sim) obj;

    boolean result = true;
    result = result && (hasMovieProfile() == other.hasMovieProfile());
    if (hasMovieProfile()) {
      result = result && getMovieProfile()
          .equals(other.getMovieProfile());
    }
    result = result && (
        Double.doubleToLongBits(getRelevance())
        == Double.doubleToLongBits(
            other.getRelevance()));
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasMovieProfile()) {
      hash = (37 * hash) + MOVIE_PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getMovieProfile().hashCode();
    }
    hash = (37 * hash) + RELEVANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getRelevance()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MovieProfile2Sim parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieProfile2Sim parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieProfile2Sim parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieProfile2Sim parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieProfile2Sim parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieProfile2Sim parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieProfile2Sim parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MovieProfile2Sim parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieProfile2Sim parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieProfile2Sim parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MovieProfile2Sim prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.MovieProfile2Sim}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.MovieProfile2Sim)
      MovieProfile2SimOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_helloworld_MovieProfile2Sim_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_helloworld_MovieProfile2Sim_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MovieProfile2Sim.class, Builder.class);
    }

    // Construct using io.grpc.examples.helloworld.MovieProfile2Sim.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (movieProfileBuilder_ == null) {
        movieProfile_ = null;
      } else {
        movieProfile_ = null;
        movieProfileBuilder_ = null;
      }
      relevance_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_helloworld_MovieProfile2Sim_descriptor;
    }

    public MovieProfile2Sim getDefaultInstanceForType() {
      return MovieProfile2Sim.getDefaultInstance();
    }

    public MovieProfile2Sim build() {
      MovieProfile2Sim result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public MovieProfile2Sim buildPartial() {
      MovieProfile2Sim result = new MovieProfile2Sim(this);
      if (movieProfileBuilder_ == null) {
        result.movieProfile_ = movieProfile_;
      } else {
        result.movieProfile_ = movieProfileBuilder_.build();
      }
      result.relevance_ = relevance_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MovieProfile2Sim) {
        return mergeFrom((MovieProfile2Sim)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MovieProfile2Sim other) {
      if (other == MovieProfile2Sim.getDefaultInstance()) return this;
      if (other.hasMovieProfile()) {
        mergeMovieProfile(other.getMovieProfile());
      }
      if (other.getRelevance() != 0D) {
        setRelevance(other.getRelevance());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MovieProfile2Sim parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MovieProfile2Sim) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private MovieProfileResponse movieProfile_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        MovieProfileResponse, MovieProfileResponse.Builder, MovieProfileResponseOrBuilder> movieProfileBuilder_;
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public boolean hasMovieProfile() {
      return movieProfileBuilder_ != null || movieProfile_ != null;
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public MovieProfileResponse getMovieProfile() {
      if (movieProfileBuilder_ == null) {
        return movieProfile_ == null ? MovieProfileResponse.getDefaultInstance() : movieProfile_;
      } else {
        return movieProfileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public Builder setMovieProfile(MovieProfileResponse value) {
      if (movieProfileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movieProfile_ = value;
        onChanged();
      } else {
        movieProfileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public Builder setMovieProfile(
        MovieProfileResponse.Builder builderForValue) {
      if (movieProfileBuilder_ == null) {
        movieProfile_ = builderForValue.build();
        onChanged();
      } else {
        movieProfileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public Builder mergeMovieProfile(MovieProfileResponse value) {
      if (movieProfileBuilder_ == null) {
        if (movieProfile_ != null) {
          movieProfile_ =
            MovieProfileResponse.newBuilder(movieProfile_).mergeFrom(value).buildPartial();
        } else {
          movieProfile_ = value;
        }
        onChanged();
      } else {
        movieProfileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public Builder clearMovieProfile() {
      if (movieProfileBuilder_ == null) {
        movieProfile_ = null;
        onChanged();
      } else {
        movieProfile_ = null;
        movieProfileBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public MovieProfileResponse.Builder getMovieProfileBuilder() {
      
      onChanged();
      return getMovieProfileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    public MovieProfileResponseOrBuilder getMovieProfileOrBuilder() {
      if (movieProfileBuilder_ != null) {
        return movieProfileBuilder_.getMessageOrBuilder();
      } else {
        return movieProfile_ == null ?
            MovieProfileResponse.getDefaultInstance() : movieProfile_;
      }
    }
    /**
     * <code>optional .helloworld.MovieProfileResponse movie_profile = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MovieProfileResponse, MovieProfileResponse.Builder, MovieProfileResponseOrBuilder>
        getMovieProfileFieldBuilder() {
      if (movieProfileBuilder_ == null) {
        movieProfileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MovieProfileResponse, MovieProfileResponse.Builder, MovieProfileResponseOrBuilder>(
                getMovieProfile(),
                getParentForChildren(),
                isClean());
        movieProfile_ = null;
      }
      return movieProfileBuilder_;
    }

    private double relevance_ ;
    /**
     * <code>optional double relevance = 2;</code>
     */
    public double getRelevance() {
      return relevance_;
    }
    /**
     * <code>optional double relevance = 2;</code>
     */
    public Builder setRelevance(double value) {
      
      relevance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double relevance = 2;</code>
     */
    public Builder clearRelevance() {
      
      relevance_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:helloworld.MovieProfile2Sim)
  }

  // @@protoc_insertion_point(class_scope:helloworld.MovieProfile2Sim)
  private static final MovieProfile2Sim DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MovieProfile2Sim();
  }

  public static MovieProfile2Sim getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieProfile2Sim>
      PARSER = new com.google.protobuf.AbstractParser<MovieProfile2Sim>() {
    public MovieProfile2Sim parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieProfile2Sim(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieProfile2Sim> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MovieProfile2Sim> getParserForType() {
    return PARSER;
  }

  public MovieProfile2Sim getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

