// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface RecommendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RecommendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string session_id = 1;</code>
   */
  String getSessionId();
  /**
   * <code>optional string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string userId = 2;</code>
   */
  String getUserId();
  /**
   * <code>optional string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated string movieId = 3;</code>
   */
  java.util.List<String>
      getMovieIdList();
  /**
   * <code>repeated string movieId = 3;</code>
   */
  int getMovieIdCount();
  /**
   * <code>repeated string movieId = 3;</code>
   */
  String getMovieId(int index);
  /**
   * <code>repeated string movieId = 3;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes(int index);

  /**
   * <code>repeated string possibility = 4;</code>
   */
  java.util.List<String>
      getPossibilityList();
  /**
   * <code>repeated string possibility = 4;</code>
   */
  int getPossibilityCount();
  /**
   * <code>repeated string possibility = 4;</code>
   */
  String getPossibility(int index);
  /**
   * <code>repeated string possibility = 4;</code>
   */
  com.google.protobuf.ByteString
      getPossibilityBytes(int index);
}
