// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface RecommendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RecommendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string session_id = 1;</code>
   */
  String getSessionId();
  /**
   * <code>optional string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string userId = 2;</code>
   */
  String getUserId();
  /**
   * <code>optional string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
