// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface similarMoviesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.similarMovies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 movie_id = 1;</code>
   */
  long getMovieId();

  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  java.util.List<MovieRelevance>
      getMovieRelevanceList();
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  MovieRelevance getMovieRelevance(int index);
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  int getMovieRelevanceCount();
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  java.util.List<? extends MovieRelevanceOrBuilder>
      getMovieRelevanceOrBuilderList();
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  MovieRelevanceOrBuilder getMovieRelevanceOrBuilder(
      int index);
}
