// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

/**
 * Protobuf type {@code helloworld.similarMovies}
 */
public  final class similarMovies extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.similarMovies)
    similarMoviesOrBuilder {
  // Use similarMovies.newBuilder() to construct.
  private similarMovies(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private similarMovies() {
    movieId_ = 0L;
    movieRelevance_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private similarMovies(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            movieId_ = input.readUInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              movieRelevance_ = new java.util.ArrayList<MovieRelevance>();
              mutable_bitField0_ |= 0x00000002;
            }
            movieRelevance_.add(
                input.readMessage(MovieRelevance.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        movieRelevance_ = java.util.Collections.unmodifiableList(movieRelevance_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_helloworld_similarMovies_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_helloworld_similarMovies_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            similarMovies.class, Builder.class);
  }

  private int bitField0_;
  public static final int MOVIE_ID_FIELD_NUMBER = 1;
  private long movieId_;
  /**
   * <code>optional uint64 movie_id = 1;</code>
   */
  public long getMovieId() {
    return movieId_;
  }

  public static final int MOVIERELEVANCE_FIELD_NUMBER = 2;
  private java.util.List<MovieRelevance> movieRelevance_;
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  public java.util.List<MovieRelevance> getMovieRelevanceList() {
    return movieRelevance_;
  }
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  public java.util.List<? extends MovieRelevanceOrBuilder>
      getMovieRelevanceOrBuilderList() {
    return movieRelevance_;
  }
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  public int getMovieRelevanceCount() {
    return movieRelevance_.size();
  }
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  public MovieRelevance getMovieRelevance(int index) {
    return movieRelevance_.get(index);
  }
  /**
   * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
   */
  public MovieRelevanceOrBuilder getMovieRelevanceOrBuilder(
      int index) {
    return movieRelevance_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (movieId_ != 0L) {
      output.writeUInt64(1, movieId_);
    }
    for (int i = 0; i < movieRelevance_.size(); i++) {
      output.writeMessage(2, movieRelevance_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (movieId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, movieId_);
    }
    for (int i = 0; i < movieRelevance_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, movieRelevance_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof similarMovies)) {
      return super.equals(obj);
    }
    similarMovies other = (similarMovies) obj;

    boolean result = true;
    result = result && (getMovieId()
        == other.getMovieId());
    result = result && getMovieRelevanceList()
        .equals(other.getMovieRelevanceList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + MOVIE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMovieId());
    if (getMovieRelevanceCount() > 0) {
      hash = (37 * hash) + MOVIERELEVANCE_FIELD_NUMBER;
      hash = (53 * hash) + getMovieRelevanceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static similarMovies parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static similarMovies parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static similarMovies parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static similarMovies parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static similarMovies parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static similarMovies parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static similarMovies parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static similarMovies parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static similarMovies parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static similarMovies parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(similarMovies prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.similarMovies}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.similarMovies)
      similarMoviesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_helloworld_similarMovies_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_helloworld_similarMovies_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              similarMovies.class, Builder.class);
    }

    // Construct using io.grpc.examples.helloworld.similarMovies.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMovieRelevanceFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      movieId_ = 0L;

      if (movieRelevanceBuilder_ == null) {
        movieRelevance_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        movieRelevanceBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_helloworld_similarMovies_descriptor;
    }

    public similarMovies getDefaultInstanceForType() {
      return similarMovies.getDefaultInstance();
    }

    public similarMovies build() {
      similarMovies result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public similarMovies buildPartial() {
      similarMovies result = new similarMovies(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.movieId_ = movieId_;
      if (movieRelevanceBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          movieRelevance_ = java.util.Collections.unmodifiableList(movieRelevance_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.movieRelevance_ = movieRelevance_;
      } else {
        result.movieRelevance_ = movieRelevanceBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof similarMovies) {
        return mergeFrom((similarMovies)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(similarMovies other) {
      if (other == similarMovies.getDefaultInstance()) return this;
      if (other.getMovieId() != 0L) {
        setMovieId(other.getMovieId());
      }
      if (movieRelevanceBuilder_ == null) {
        if (!other.movieRelevance_.isEmpty()) {
          if (movieRelevance_.isEmpty()) {
            movieRelevance_ = other.movieRelevance_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMovieRelevanceIsMutable();
            movieRelevance_.addAll(other.movieRelevance_);
          }
          onChanged();
        }
      } else {
        if (!other.movieRelevance_.isEmpty()) {
          if (movieRelevanceBuilder_.isEmpty()) {
            movieRelevanceBuilder_.dispose();
            movieRelevanceBuilder_ = null;
            movieRelevance_ = other.movieRelevance_;
            bitField0_ = (bitField0_ & ~0x00000002);
            movieRelevanceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMovieRelevanceFieldBuilder() : null;
          } else {
            movieRelevanceBuilder_.addAllMessages(other.movieRelevance_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      similarMovies parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (similarMovies) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long movieId_ ;
    /**
     * <code>optional uint64 movie_id = 1;</code>
     */
    public long getMovieId() {
      return movieId_;
    }
    /**
     * <code>optional uint64 movie_id = 1;</code>
     */
    public Builder setMovieId(long value) {
      
      movieId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 movie_id = 1;</code>
     */
    public Builder clearMovieId() {
      
      movieId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<MovieRelevance> movieRelevance_ =
      java.util.Collections.emptyList();
    private void ensureMovieRelevanceIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        movieRelevance_ = new java.util.ArrayList<MovieRelevance>(movieRelevance_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieRelevance, MovieRelevance.Builder, MovieRelevanceOrBuilder> movieRelevanceBuilder_;

    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public java.util.List<MovieRelevance> getMovieRelevanceList() {
      if (movieRelevanceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movieRelevance_);
      } else {
        return movieRelevanceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public int getMovieRelevanceCount() {
      if (movieRelevanceBuilder_ == null) {
        return movieRelevance_.size();
      } else {
        return movieRelevanceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public MovieRelevance getMovieRelevance(int index) {
      if (movieRelevanceBuilder_ == null) {
        return movieRelevance_.get(index);
      } else {
        return movieRelevanceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder setMovieRelevance(
        int index, MovieRelevance value) {
      if (movieRelevanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieRelevanceIsMutable();
        movieRelevance_.set(index, value);
        onChanged();
      } else {
        movieRelevanceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder setMovieRelevance(
        int index, MovieRelevance.Builder builderForValue) {
      if (movieRelevanceBuilder_ == null) {
        ensureMovieRelevanceIsMutable();
        movieRelevance_.set(index, builderForValue.build());
        onChanged();
      } else {
        movieRelevanceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder addMovieRelevance(MovieRelevance value) {
      if (movieRelevanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieRelevanceIsMutable();
        movieRelevance_.add(value);
        onChanged();
      } else {
        movieRelevanceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder addMovieRelevance(
        int index, MovieRelevance value) {
      if (movieRelevanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieRelevanceIsMutable();
        movieRelevance_.add(index, value);
        onChanged();
      } else {
        movieRelevanceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder addMovieRelevance(
        MovieRelevance.Builder builderForValue) {
      if (movieRelevanceBuilder_ == null) {
        ensureMovieRelevanceIsMutable();
        movieRelevance_.add(builderForValue.build());
        onChanged();
      } else {
        movieRelevanceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder addMovieRelevance(
        int index, MovieRelevance.Builder builderForValue) {
      if (movieRelevanceBuilder_ == null) {
        ensureMovieRelevanceIsMutable();
        movieRelevance_.add(index, builderForValue.build());
        onChanged();
      } else {
        movieRelevanceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder addAllMovieRelevance(
        Iterable<? extends MovieRelevance> values) {
      if (movieRelevanceBuilder_ == null) {
        ensureMovieRelevanceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movieRelevance_);
        onChanged();
      } else {
        movieRelevanceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder clearMovieRelevance() {
      if (movieRelevanceBuilder_ == null) {
        movieRelevance_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        movieRelevanceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public Builder removeMovieRelevance(int index) {
      if (movieRelevanceBuilder_ == null) {
        ensureMovieRelevanceIsMutable();
        movieRelevance_.remove(index);
        onChanged();
      } else {
        movieRelevanceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public MovieRelevance.Builder getMovieRelevanceBuilder(
        int index) {
      return getMovieRelevanceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public MovieRelevanceOrBuilder getMovieRelevanceOrBuilder(
        int index) {
      if (movieRelevanceBuilder_ == null) {
        return movieRelevance_.get(index);  } else {
        return movieRelevanceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public java.util.List<? extends MovieRelevanceOrBuilder>
         getMovieRelevanceOrBuilderList() {
      if (movieRelevanceBuilder_ != null) {
        return movieRelevanceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movieRelevance_);
      }
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public MovieRelevance.Builder addMovieRelevanceBuilder() {
      return getMovieRelevanceFieldBuilder().addBuilder(
          MovieRelevance.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public MovieRelevance.Builder addMovieRelevanceBuilder(
        int index) {
      return getMovieRelevanceFieldBuilder().addBuilder(
          index, MovieRelevance.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.MovieRelevance movieRelevance = 2;</code>
     */
    public java.util.List<MovieRelevance.Builder>
         getMovieRelevanceBuilderList() {
      return getMovieRelevanceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieRelevance, MovieRelevance.Builder, MovieRelevanceOrBuilder>
        getMovieRelevanceFieldBuilder() {
      if (movieRelevanceBuilder_ == null) {
        movieRelevanceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MovieRelevance, MovieRelevance.Builder, MovieRelevanceOrBuilder>(
                movieRelevance_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        movieRelevance_ = null;
      }
      return movieRelevanceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:helloworld.similarMovies)
  }

  // @@protoc_insertion_point(class_scope:helloworld.similarMovies)
  private static final similarMovies DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new similarMovies();
  }

  public static similarMovies getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<similarMovies>
      PARSER = new com.google.protobuf.AbstractParser<similarMovies>() {
    public similarMovies parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new similarMovies(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<similarMovies> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<similarMovies> getParserForType() {
    return PARSER;
  }

  public similarMovies getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

