// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface UserRatingListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.UserRatingList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 movie_id = 1;</code>
   */
  long getMovieId();

  /**
   * <code>optional double rating = 2;</code>
   */
  double getRating();

  /**
   * <code>optional uint64 timestamp = 3;</code>
   */
  long getTimestamp();
}
