// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld;

public interface UserProfileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.UserProfileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string session_id = 1;</code>
   */
  String getSessionId();
  /**
   * <code>optional string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional uint64 user_id = 2;</code>
   */
  long getUserId();

  /**
   * <code>repeated .helloworld.UserRatingList ratingList = 3;</code>
   */
  java.util.List<UserRatingList>
      getRatingListList();
  /**
   * <code>repeated .helloworld.UserRatingList ratingList = 3;</code>
   */
  UserRatingList getRatingList(int index);
  /**
   * <code>repeated .helloworld.UserRatingList ratingList = 3;</code>
   */
  int getRatingListCount();
  /**
   * <code>repeated .helloworld.UserRatingList ratingList = 3;</code>
   */
  java.util.List<? extends UserRatingListOrBuilder>
      getRatingListOrBuilderList();
  /**
   * <code>repeated .helloworld.UserRatingList ratingList = 3;</code>
   */
  UserRatingListOrBuilder getRatingListOrBuilder(
      int index);

  /**
   * <code>repeated .helloworld.MovieTag tags = 4;</code>
   */
  java.util.List<MovieTag>
      getTagsList();
  /**
   * <code>repeated .helloworld.MovieTag tags = 4;</code>
   */
  MovieTag getTags(int index);
  /**
   * <code>repeated .helloworld.MovieTag tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .helloworld.MovieTag tags = 4;</code>
   */
  java.util.List<? extends MovieTagOrBuilder>
      getTagsOrBuilderList();
  /**
   * <code>repeated .helloworld.MovieTag tags = 4;</code>
   */
  MovieTagOrBuilder getTagsOrBuilder(
      int index);

  /**
   * <code>optional double average_rating = 5;</code>
   */
  double getAverageRating();

  /**
   * <code>optional string prefer_year = 6;</code>
   */
  String getPreferYear();
  /**
   * <code>optional string prefer_year = 6;</code>
   */
  com.google.protobuf.ByteString
      getPreferYearBytes();

  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 7;</code>
   */
  java.util.List<MovieTag>
      getSortedTagsList();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 7;</code>
   */
  MovieTag getSortedTags(int index);
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 7;</code>
   */
  int getSortedTagsCount();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 7;</code>
   */
  java.util.List<? extends MovieTagOrBuilder>
      getSortedTagsOrBuilderList();
  /**
   * <code>repeated .helloworld.MovieTag sortedTags = 7;</code>
   */
  MovieTagOrBuilder getSortedTagsOrBuilder(
      int index);
}
